export const countries = [
  { label: 'Albania', value: 'AL' },
  { label: 'Alemania', value: 'DE' },
  { label: 'Andorra', value: 'AD' },
  { label: 'Arabia Saudí', value: 'SA' },
  { label: 'Argentina', value: 'AR' },
  { label: 'Australia', value: 'AU' },
  { label: 'Austria', value: 'AT' },
  { label: 'Baréin', value: 'BH' },
  { label: 'Brasil', value: 'BR' },
  { label: 'Bulgaria', value: 'BG' },
  { label: 'Camboya', value: 'KH' },
  { label: 'Canadá', value: 'CA' },
  { label: 'Catar', value: 'QA' },
  { label: 'Chile', value: 'CL' },
  { label: 'Chipre', value: 'CY' },
  { label: 'Colombia', value: 'CO' },
  { label: 'Corea del Sur', value: 'KR' },
  { label: 'Egipto', value: 'EG' },
  { label: 'Emiratos Árabes Unidos', value: 'AE' },
  { label: 'España', value: 'ES' },
  { label: 'Estados Unidos', value: 'US' },
  { label: 'Filipinas', value: 'PH' },
  { label: 'Francia', value: 'FR' },
  { label: 'Georgia', value: 'GE' },
  { label: 'Grecia', value: 'GR' },
  { label: 'Hong Kong', value: 'HK' },
  { label: 'Hungría', value: 'HU' },
  { label: 'Irán', value: 'IR' },
  { label: 'Irlanda', value: 'IE' },
  { label: 'Italia', value: 'IT' },
  { label: 'Japón', value: 'JP' },
  { label: 'Jordania', value: 'JO' },
  { label: 'Malasia', value: 'MY' },
  { label: 'Macao', value: 'MO' },
  { label: 'Marruecos', value: 'MA' },
  { label: 'México', value: 'MX' },
  { label: 'Países Bajos', value: 'NL' },
  { label: 'Polonia', value: 'PL' },
  { label: 'Portugal', value: 'PT' },
  { label: 'Puerto Rico', value: 'PR' },
  { label: 'Reino Unido', value: 'GB' },
  { label: 'República Dominicana', value: 'DO' },
  { label: 'Sudáfrica', value: 'ZA' },
  { label: 'Suecia', value: 'SE' },
  { label: 'Tailandia', value: 'TH' },
  { label: 'Taiwán', value: 'TW' },
  { label: 'Túnez', value: 'TN' },
  { label: 'Turquía', value: 'TR' },
  { label: 'Uzbekistán', value: 'UZ' },
  { label: 'Vietnam', value: 'VN' }
];
